### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by LinLuosheng** [guibacellar/TEx#15]
. Consider execute "load_groups" command to perform a full group synchronization (Members and Group Cover Photo).
2023-10-06 16:39:59,248 - ERROR - Unhandled exception on __handler
Traceback (most recent call last):
  File "C:\Users\48242\AppData\Roaming\Python\Python310\site-packages\telethon\client\updates.py", line 570, in _dispatch_update
    await callback(event)
  File "C:\Users\48242\AppData\Roaming\Python\Python310\site-packages\TEx\modules\telegram_messages_listener.py", line 48, in __handler
    await self.__ensure_group_exists(event=event)
  File "C:\Users\48242\AppData\Roaming\Python\Python310\site-packages\TEx\modules\telegram_messages_listener.py", line 120, in __ensure_group_exists
    group_dict_data: Dict = TelethonChannelEntityMapper.to_database_dict(
  File "C:\Users\48242\AppData\Roaming\Python\Python310\site-packages\TEx\core\mapper\telethon_channel_mapper.py", line 19, in to_database_dict
    'gigagroup': channel.gigagroup if channel.gigagroup else False,
AttributeError: 'User' object has no attribute 'gigagroup'
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\48242\AppData\Roaming\Python\Python310\site-packages\TEx\__main__.py", line 22, in <module>
    sys.exit(TelegramMonitorRunner().main())
  File "C:\Users\48242\AppData\Roaming\Python\Python310\site-packages\TEx\runner.py", line 70, in main
    self.__execute_sequence(args, data, self.config['PIPELINE']['pipeline_sequence'].split('\n'), 'Pipeline')
  File "C:\Users\48242\AppData\Roaming\Python\Python310\site-packages\TEx\runner.py", line 101, in __execute_sequence
    loop.run_until_complete(
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1845, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 434, in select
    self._poll(timeout)
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 783, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)

**Comment by guibacellar** [comment]
Hi @LinLuosheng 

I'm trying to reproduce the behavior's, but unsuccessfully. Can you explain a little bit about your account (obviously with exposing your account).

Are you talking with a bot (Any one) in this account?
Is there anything that seems strange or unusual in your chats, or groups? Like a non chat group (crazy, but can happen)

**Comment by guibacellar** [comment]
This issue are fixed on V0.2.15. Please update your version and try

```bash
pip install --upgrade TelegramExplorer
```
